### ISSUE TITLE
PM-009: Add job submission form React component

### ISSUE THREAD

**Issue by xenioushk** [jahidbinkibria/group23_Pocket_Money#27]
![Image](https://user-images.githubusercontent.com/1782254/200072299-f3a9e59e-e611-4fcb-993f-b339ab18641f.png)

**Comment by djsaint03** [comment]
![Image](https://user-images.githubusercontent.com/15379037/205439952-7ea296ec-599a-462d-83d3-bd26bfbea032.png)
