### ISSUE TITLE
PM-031: Add category field to job submission form

### ISSUE THREAD

**Issue by xenioushk** [jahidbinkibria/group23_Pocket_Money#55]
![Image](https://user-images.githubusercontent.com/1782254/200177770-788d098a-8b88-48e5-a10a-942310238614.png)

**Comment by djsaint03** [comment]
updated view

![Image](https://user-images.githubusercontent.com/15379037/205440284-d0ab8a9f-c0fd-437a-b546-208b48e254ae.png)
