### ISSUE TITLE
PM-034: Remove “task” text from the home page job list.

### ISSUE THREAD

**Issue by xenioushk** [jahidbinkibria/group23_Pocket_Money#71]
![Image](https://user-images.githubusercontent.com/1782254/201614858-39ec07e7-a202-45cb-a370-6781bb3f5cc6.png)

**Comment by djsaint03** [comment]
NEW VIEW

![Image](https://user-images.githubusercontent.com/15379037/205440546-592017ff-ef4b-49c4-b4a8-4b2ff8e1b27d.png)
