### ISSUE TITLE
PM-035: Add task price in home page job list

### ISSUE THREAD

**Issue by xenioushk** [jahidbinkibria/group23_Pocket_Money#86]
![Image](https://user-images.githubusercontent.com/1782254/201771535-923523ea-54e0-4777-86d3-443e9ea553ea.png)

**Comment by djsaint03** [comment]
updated

![Image](https://user-images.githubusercontent.com/15379037/205441100-569c1024-2dc6-47c6-b9ba-21d4b384bd56.png)
